package mchorse.blockbuster.client.model.parsing;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import javax.vecmath.Matrix3f;
import javax.vecmath.Matrix4f;
import javax.vecmath.Vector3f;
import javax.vecmath.Vector4f;

import mchorse.blockbuster.Blockbuster;
import mchorse.blockbuster.api.Model;
import mchorse.blockbuster.api.ModelLimb;
import mchorse.blockbuster.api.ModelPose;
import mchorse.blockbuster.api.ModelTransform;

/**
 * Model exporter OBJ class (P74).
 *
 * <p>Converts a Blockbuster JSON {@link Model} into Wavefront OBJ text. This is a
 * faithful, fully-headless port of 1.12.2's
 * {@code mchorse.blockbuster.client.model.parsing.ModelExporterOBJ}: the matrix
 * math still runs through {@code javax.vecmath} (bundled per the P13 decision) so
 * the composition order, float rounding and {@code Vector4f.indexOf} vertex-dedup
 * behaviour are bit-for-bit identical to the legacy exporter. The only two
 * documented deviations from 1.12.2 are:</p>
 *
 * <ul>
 *   <li>Geometry comes from the self-contained {@link BoxGeometry} instead of
 *       vanilla {@code ModelBox} + a reflected private {@code TexturedQuad[]}
 *       field (the vanilla classes are gone in 1.20.4); {@link BoxGeometry}
 *       reproduces the exact vertex/quad/UV generation, so the emitted geometry
 *       is unchanged.</li>
 *   <li>All {@code String.format} calls are pinned to {@link Locale#ROOT} (P74
 *       open-question 7). 1.12.2 used the default locale, which produced broken
 *       comma-decimal OBJs on non-dot locales; that broken output is not
 *       load-bearing, so we fix it deterministically.</li>
 * </ul>
 *
 * <p>Matrix conventions kept verbatim: translation with negated Y/Z
 * ({@code m23 = -m23; m13 = -m13}), rotation composed <b>Z(-rz)·Y(-ry)·X(+rx)</b>,
 * scale on the diagonal, parent-chain accumulation, a global downscale/flip
 * ({@code scale.rotZ(PI); setScale(1/16)}), a normal flip ({@code r.m11 = -1}),
 * per-limb vertex dedup, and {@code %.4f} vertices/normals with {@code %f} UVs
 * (the {@code 1 - v} texture flip).</p>
 */
public class ModelExporterOBJ
{
    private Model data;
    private ModelPose pose;

    public ModelExporterOBJ(Model data, ModelPose pose)
    {
        this.data = data;
        this.pose = pose;
    }

    /**
     * Export given model into OBJ string
     */
    public String export(String modelName)
    {
        String obj = "# OBJ generated by Blockbuster (version " + Blockbuster.VERSION + ")\n\nmtllib " + modelName + ".mtl\nusemtl default\n";

        Map<ModelLimb, Mesh> meshes = new HashMap<>();
        this.generateMeshes(meshes);

        return obj + this.generateBody(meshes);
    }

    /**
     * Prepare and generate meshes. This method is responsible for
     * turning model's limbs into boxes and also preparing
     * transformation matrices for actual generation of OBJ geometry.
     */
    private void generateMeshes(Map<ModelLimb, Mesh> meshes)
    {
        float textureWidth = this.data.texture[0];
        float textureHeight = this.data.texture[1];

        for (ModelLimb limb : this.data.limbs.values())
        {
            ModelTransform transform = this.pose.limbs.get(limb.name);

            if (transform == null)
            {
                transform = ModelTransform.DEFAULT;
            }

            Matrix4f mat = new Matrix4f();
            mat.setIdentity();
            Matrix3f rotScale = new Matrix3f();
            rotScale.setIdentity();
            mat.setTranslation(new Vector3f(transform.translate));
            mat.m23 = -mat.m23;
            mat.m13 = -mat.m13;

            Matrix3f x = new Matrix3f();
            rotScale.m00 = transform.scale[0];
            rotScale.m11 = transform.scale[1];
            rotScale.m22 = transform.scale[2];

            Matrix3f rot = new Matrix3f();
            rot.setIdentity();
            x.setIdentity();
            x.rotZ((float) Math.toRadians(-transform.rotate[2]));
            rot.mul(x);
            x.setIdentity();
            x.rotY((float) Math.toRadians(-transform.rotate[1]));
            rot.mul(x);
            x.setIdentity();
            x.rotX((float) Math.toRadians(transform.rotate[0]));
            rot.mul(x);

            rotScale.mul(rot);
            mat.setRotationScale(rotScale);

            int w = limb.size[0];
            int h = limb.size[1];
            int d = limb.size[2];

            float ox = 1 - limb.anchor[0];
            float oy = limb.anchor[1];
            float oz = limb.anchor[2];

            BoxGeometry box = new BoxGeometry(limb.texture[0], limb.texture[1], -w * ox, -h * oy, -d * oz, w, h, d, limb.sizeOffset, limb.mirror, textureWidth, textureHeight);

            meshes.put(limb, new Mesh(box, mat, rot));
        }
    }

    /**
     * Generate body of the OBJ file based on given prepared meshes
     */
    private String generateBody(Map<ModelLimb, Mesh> meshes)
    {
        String output = "";
        /* Count of vertices, normals and UVs indices */
        int v = 1;
        int u = 1;
        int n = 1;

        Matrix4f scale = new Matrix4f();
        scale.setIdentity();
        scale.rotZ((float) Math.PI);
        scale.setScale(1 / 16F);

        for (Map.Entry<ModelLimb, Mesh> entry : meshes.entrySet())
        {
            ModelLimb limb = entry.getKey();
            Mesh mesh = entry.getValue();
            BoxGeometry.Quad[] quads = mesh.box.quads;

            /* Technically shouldn't ever happen, but just in case */
            if (quads == null) continue;

            Matrix4f mat = new Matrix4f(mesh.mat);
            Matrix3f rot = new Matrix3f(mesh.rot);

            if (!limb.parent.isEmpty())
            {
                ModelLimb parent = this.data.limbs.get(limb.parent);

                while (parent != null)
                {
                    Mesh parentMesh = meshes.get(parent);
                    Matrix4f mat2 = new Matrix4f(parentMesh.mat);
                    Matrix3f rot2 = new Matrix3f(parentMesh.rot);

                    mat2.mul(mat);
                    rot2.mul(rot);

                    mat = mat2;
                    rot = rot2;

                    parent = this.data.limbs.get(parent.parent);
                }
            }

            /* Downscale geometry and flip vertically */
            Matrix4f m = new Matrix4f(scale);
            m.mul(mat);
            mat = m;

            /* Flip vertically normals */
            Matrix3f r = new Matrix3f();
            r.setIdentity();
            r.m11 = -1;
            r.mul(rot);
            rot = r;

            output += "o " + limb.name.replaceAll("\\s", "_") + "\n";

            String vertices = "";
            String normals = "";
            String uvs = "";
            String faces = "";

            /* List of already added vectors, so we could make connected
             * vertices, instead of separate faces (i.e. to simplify the work
             * on the modeler to do the remove doubles on every limb) */
            List<Vector4f> vecs = new ArrayList<Vector4f>();

            for (BoxGeometry.Quad quad : quads)
            {
                /* Calculating normal as done in TexturedQuad */
                double[] v1 = subtractReverse(quad.vertexPositions[1], quad.vertexPositions[0]);
                double[] v2 = subtractReverse(quad.vertexPositions[1], quad.vertexPositions[2]);
                double[] v3 = normalize(crossProduct(v2, v1));
                Vector3f normal = new Vector3f((float) v3[0], (float) v3[1], (float) v3[2]);
                String face = "f ";

                rot.transform(normal);
                normal.normalize();
                normals += String.format(Locale.ROOT, "vn %.4f %.4f %.4f\n", normal.x, normal.y, normal.z);

                /* We're iterating backward, because it's important for
                 * normal generation. */
                for (int i = 0; i < quad.nVertices; i++)
                {
                    BoxGeometry.Vertex vx = quad.vertexPositions[i];
                    Vector4f vec = new Vector4f((float) vx.x, (float) vx.y, (float) vx.z, 1);

                    mat.transform(vec);

                    /* Find vector index */
                    int vi = vecs.indexOf(vec);

                    if (vi == -1)
                    {
                        /* If vector index is not found, add it and write it */
                        vertices += String.format(Locale.ROOT, "v %.4f %.4f %.4f\n", vec.x, vec.y, vec.z);
                        vi = vecs.size();
                        vecs.add(vec);
                    }

                    uvs += String.format(Locale.ROOT, "vt %f %f\n", vx.texturePositionX, 1 - vx.texturePositionY);
                    face += (v + vi) + "/" + u + "/" + n + " ";

                    u++;
                }

                faces += face.trim() + "\n";
                n++;
            }

            v += vecs.size();

            output += vertices + normals + uvs + faces;
        }

        return output;
    }

    /**
     * {@code a.subtractReverse(b)} from 1.12.2 {@code Vec3d}: returns
     * {@code b - a}.
     */
    private static double[] subtractReverse(BoxGeometry.Vertex a, BoxGeometry.Vertex b)
    {
        return new double[] {b.x - a.x, b.y - a.y, b.z - a.z};
    }

    /**
     * {@code a.crossProduct(b)} from 1.12.2 {@code Vec3d}.
     */
    private static double[] crossProduct(double[] a, double[] b)
    {
        return new double[] {
            a[1] * b[2] - a[2] * b[1],
            a[2] * b[0] - a[0] * b[2],
            a[0] * b[1] - a[1] * b[0]
        };
    }

    /**
     * {@code Vec3d.normalize()} from 1.12.2: below a 1e-4 magnitude returns the
     * zero vector.
     */
    private static double[] normalize(double[] a)
    {
        double d = Math.sqrt(a[0] * a[0] + a[1] * a[1] + a[2] * a[2]);

        return d < 1.0E-4D ? new double[] {0.0D, 0.0D, 0.0D} : new double[] {a[0] / d, a[1] / d, a[2] / d};
    }

    /**
     * Temporary mesh structure which is used internally within this
     * class for generating an OBJ
     */
    public static class Mesh
    {
        public BoxGeometry box;
        public Matrix4f mat;
        public Matrix3f rot;

        public Mesh(BoxGeometry box, Matrix4f mat, Matrix3f rot)
        {
            this.box = box;
            this.mat = mat;
            this.rot = rot;
        }
    }
}
